runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: i6E91keCPEHafsFgEz90b3exDRfnCi5s
  STORAGE_DIR: /tmp
